version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proyecto_grupal_web
    ports:
      - "8080:80"  # http://localhost:8081
    
    restart: unless-stopped
